services:
  db:
    image: mysql:8.0
    container_name: storage-service-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 33061:3306
    networks:
      - storage-service-net
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  web:
    image: nginx:1.27.2
    container_name: storage-service-web
    restart: always
    ports:
      - 8001:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public/index.php:/app/public/index.php
    networks:
      - storage-service-net
      - docker-net

  app:
    build:
      context: ./
      target: dev
    container_name: storage-service-app
    restart: always
    volumes:
      - ./:/app
    environment:
      GITHUB_API_TOKEN: ${GITHUB_API_TOKEN}
    networks:
      - storage-service-net
      - docker-net

networks:
  storage-service-net:
    driver: 'bridge'
  docker-net:
    external: true
volumes:
  db-data: